---
- name: Configure Raspberry Pi systems with quality tester-software
  hosts: raspberry-pi-inventory
  gather_facts: true
  become: yes
  vars_files:
    - credentials.yml

  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  tasks:
    # Reboot to ensure that the raspberry pi desktop is atually installed and gets booted into
    - name: Reboot the device
      reboot:
        reboot_timeout: 3600

    - name: Update apt cache
      apt:
        # upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - python3
          - python3-pip
          - pcmanfm
          - matchbox-keyboard
        state: present

    - name: Copy background image
      copy:
        src: ./wallpaper.png
        dest: /home/pi/Documents/wallpaper.png
      become_user: pi

    - name: Set the wallpaper
      command: pcmanfm --set-wallpaper '/home/pi/Documents/wallpaper.png'
      environment:
        DISPLAY: ":0.0"
      become_user: pi

    - name: Ensure destination directory is absent
      file:
        path: /home/pi/quality-tester
        state: absent
      become_user: pi

    - name: Clone the repository
      git:
        repo: https://github.com/jmacenka/quality-tester
        dest: /home/pi/quality-tester
        clone: yes
        update: yes
      become_user: pi

    - name: Install Python requirements
      pip:
        requirements: /home/pi/quality-tester/src/quality-tester/requirements.txt
      become_user: pi

    - name: Ensure config values in /boot/config.txt
      lineinfile:
        path: /boot/config.txt
        line: "{{ item }}"
      loop:
        - gpu_mem=256

        # # Resolution 1600x900
        # - hdmi_cvt=1600 900 60
        # - hdmi_group=2
        # - hdmi_mode=87

        # Resolution 1024x768
        - hdmi_group=2
        - hdmi_mode=16

    - name: Copy quality-tester.service
      template:
        src: quality-tester.service.j2
        dest: /etc/systemd/system/quality-tester.service

    - name: Start and enable quality-tester service
      systemd:
        name: quality-tester
        enabled: yes
        state: started

    - name: Create autostart directory
      file:
        path: "/home/pi/.config/autostart/"
        state: directory

    - name: Create start_browser.desktop script
      copy:
        content: |
          [Desktop Entry]
          Type=Application
          Name=Start Browser
          Exec=sh -c "xdg-open http://localhost:8080"
          X-GNOME-Autostart-enabled=true

        dest: /home/pi/.config/autostart/start_browser.desktop

    - name: Reboot the device
      reboot:
        reboot_timeout: 3600

    # - name: Shut down the device
    #   command:
    #     cmd: "shutdown -h now"
    #   become: yes
    #   async: 1
    #   poll: 0